version: 0.1
phase:
  install:
    commands:
      - aws cloudformation package --template-file SAM_template.yml --s3-bucket lambda-pipeline --output-template-file outputSamTemplate.yml
artifacts:
  type: zip
  files:
    -SAM_template.yml
    -outputSamTemplate.yml
