AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2019-28-04'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
    Handler: lambda_function.lambda_handler
    Runtime: python3.6
    CodeUri: ./codepipelinedeployment
    Description: Lambda Function for CD demo
    MemorySize: 128
    Timeout: 30
    Role: 'arn:aws:iam::424006611070:role/CloudFormationServiceRole'
    Events:
      getAZsAPI:
        Type: Api
        Properties:
          Path: /getazs
          Method: get
    Environment:
      Variables:
        Region: us-west-2

